### ISSUE TITLE
Bug - Staff and Contributers card

### ISSUE THREAD

**Issue by Kira272921** [ASEAN-Build-The-Earth/AseanBTE-Website#34]
The staff and contributers cards seems to go vertical in tablet landscape mode,  and it seems really odd

It would be great if anyone would be able to make it look horizontal with 3 cards in a row 
![Screenshot_20211025-194144](https://user-images.githubusercontent.com/90365542/138711992-594685d1-d99a-43fa-b5e6-4dab41144fb4.png)
[Here](https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/blob/915ed41f4991eeae488d5a02dcffafa6f94f3bc7/Staff_and_Contributors) is the link to the folder of staff and contributers

**Comment by tintinkung** [comment]
> Has this bug been fixed yet? Asking as I see it still open.

I think i just open it for too long

**Comment by tintinkung** [comment]
- [x] last updated: discussion ended
   - `status: fixed`, 99% fixed 
   - only rare case with very tall screen can get this issue(the 1%)
