### ISSUE TITLE
site not found ! 

### ISSUE THREAD

**Issue by pratap360** [ASEAN-Build-The-Earth/AseanBTE-Website#65]
![image](https://user-images.githubusercontent.com/52885495/139589245-44f1a11b-375a-4116-ab2b-81bc790a97ac.png)

**there is an issue with the link or github host or some thing like that ? 
while clicking the [link](https://asean-build-the-earth.github.io/AseanBTE-Website/) it show site not found as per the screen shot provided above**
this same link can be found from the about section of this repo.. 
this issue must fix asap

**Comment by StoneMcYT** [comment]
> ![image](https://user-images.githubusercontent.com/52885495/139589245-44f1a11b-375a-4116-ab2b-81bc790a97ac.png)
> 
> **there is an issue with the link or github host or some thing like that ? while clicking the [link](https://asean-build-the-earth.github.io/AseanBTE-Website/) it show site not found as per the screen shot provided above**

Ah yes my apologies we haven't updated the readme yet we are trying to migrate to netify at the moment

https://asean-bte.netlify.app

**Comment by pratap360** [comment]
ok no problem 😃 👍

**Comment by StoneMcYT** [comment]
Issue has just been fixed by us. Thanks for spotting the issue!

**Comment by pratap360** [comment]
welcome 👍🏼
